### ISSUE TITLE
Change to display the text link by default in the index page

### ISSUE THREAD

**Issue by koirand** [koirand/pulp#42]
In the index page, Pulp theme seem to be used by not only icon link but also with text link by user customize.
So change to display the text link by default.

**Comment by koirand** [comment]
I Added identifier attribute in config.toml.
From now, Please use the name attribute to display a text link.

with text link example
``` toml
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10
```
<img width="450" alt="Site_Title" src="https://user-images.githubusercontent.com/17229643/57196410-9e69f600-6f97-11e9-9dcb-c5f0fa112009.png">

only icon link example
``` toml
[[menu.main]]
    identifier = "blog"
    # name = "Blog"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10
```
<img width="450" alt="Site_Title" src="https://user-images.githubusercontent.com/17229643/57196451-f43e9e00-6f97-11e9-8269-1d1b4db75f03.png">
